### ISSUE TITLE
Multiple selectors supported?

### ISSUE THREAD

**Issue by layershifter** [robinweser/fela#723]
## Bug

| Packages | Version |
| -------- | ------- |
| fela     | 10.5.x   |

## Description

I am not sure that it's a real bug, but I need some clarification around it. In LESS (_any other preprocessor_) I can do following:
```less
.a {
  :hover, :focus {
    background: red
  }
}
```
Which will produce:
```css
.a :hover,
.a :focus {
  background: red;
}
```

I have not seen this anywhere in docs, but when I tried to do the same:
```js
createComponent(
  () => ({
    ":hover,:focus": {
      background: "red"
    }
  }),
  "button"
)
```

But Fela outputs 💣
```css
.a:hover, :focus {
  background: red
}
```

There is no `a` class for `:focus`, so this style will be applied to any element:

![image](https://user-images.githubusercontent.com/14183168/61302567-4ac12780-a7e6-11e9-9613-a3975db8bec1.png)

### Test case

https://codesandbox.io/s/react-fela-h8eu8
